language: cpp

compiler:
  - clang
  #- gcc

osx_image: xcode7
os:
  - osx
  #- linux

git:
  submodules: false

env:
  - TARGET_ARCH=x64

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang
    - cmake

before_install:
  - export PATH=$(pwd)/cmake/bin:$PATH
  - git submodule update --init --recursive

before_script:
  - cmake --version
  - cmake -DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=OFF .

script: make
