language: cpp

compiler:
  - gcc

before_install:
  - wget http://pkgs.fedoraproject.org/repo/pkgs/cmake/cmake-3.2.2.tar.gz/2da57308071ea98b10253a87d2419281/cmake-3.2.2.tar.gz
  - tar -xzf cmake-3.2.2.tar.gz
  - rm cmake-3.2.2.tar.gz
  - export PATH=$(pwd)/cmake/bin:$PATH

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

script: make
