language: cpp

os:
  - osx

compiler:
    - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

install:
  - wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.4.3-Linux-x86_64.tar.gz
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
    - mkdir build
    - cd build
    - ./cmake-3.4.3-Linux-x86_64/bin/cmake .. --config Debug
