language: cpp
compiler:
  - clang
  - gcc
os: linux
sudo: false


git:
  submodules: false

env:
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - os: linux
    - env: COMPILER=g++-4.8 CMAKE_OPTIONS="-DJSONCPP_LIB_BUILD_STATIC=ON -DJSONCPP_LIB_BUILD_SHARED=OFF"
        addons:
          apt:
            packages: ["g++-4.8"]
            sources:
              - ubuntu-toolchain-r-test

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

before_install:
  - set -e # Fail the whole script whenever any command fails
  - git submodule update --init --recursive

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - (mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} ${CMAKE_OPTIONS})

script:
  - ${TRAVIS_BUILD_DIR}/ChiikaAPI/ThirdParty/log4cplus/configure
  - cd ${TRAVIS_BUILD_DIR}
  - cd build && make
