language: cpp

compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

git:
  submodules: false

env:
  - TARGET_ARCH=x64


before_install:
  - git submodule update --init --recursive
  - wget --no-check-certificate http://cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.tar.gz
  - tar -xzvf cmake-3.2.2-Linux-x86_64.tar.gz
  - rm cmake-3.2.2-Linux-x86_64.tar.gz
  - export PATH=$(pwd)/cmake/bin:$PATH
  - if [ "$CXX" = "g++" ]; then export CXX="gcc-4.9"; fi

before_script:
  - ./cmake-3.2.2-Linux-x86_64/bin/cmake --version
  - mkdir build
  - ./cmake-3.2.2-Linux-x86_64/bin/cmake .

script: make
