//----------------------------------------------------------------------------
//Chiika Api
//Copyright (C) 2015  Alperen Gezer
//This program is free software; you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation; either version 2 of the License, or
//(at your option) any later version.
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.
//You should have received a copy of the GNU General Public License along
//with this program; if not, write to the Free Software Foundation, Inc.,
//51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.*/
//----------------------------------------------------------------------------
#include "Stable.h"
#include "MalScrape.h"
#include "Database\LocalDataManager.h"
#include "Root\Root.h"
#include "Logging\ChiString.h"
#include "Logging\LogManager.h"
//----------------------------------------------------------------------------
namespace ChiikaApi
{
	MalScrapeRequest::MalScrapeRequest()
	{
		m_sName = kRequestVerify;
	}
	//----------------------------------------------------------------------------
	MalScrapeRequest::~MalScrapeRequest()
	{
	}
	//----------------------------------------------------------------------------
	void MalScrapeRequest::OnSuccess()
	{
#pragma region stuff
		ChiString output = "\n"
			"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html><head>\n"
			"        \n"
			"\n"
			"<title>\n"
			"arkenthera&#039;s Profile - MyAnimeList.net\n"
			"</title>\n"
			"<meta name=\"description\" content=\"Check out arkenthera&#039;s anime and manga lists, stats, favorites and so much more on MyAnimeList, the largest online anime and manga database in the world! Join the online community, create your anime and manga list, read reviews, explore the forums, follow news, and so much more!\" />\n"
			"\n"
			"  \n"
			"<meta name=\"keywords\" content=\"anime, myanimelist, anime news, manga\" />\n"
			"  \n"
			"\n"
			"<meta name='csrf_token' content='75f8a97437f1b3719aec0dc070fe69864c9f8927'><script type=\"text/javascript\" src=\"http://cdn.myanimelist.net/static/assets/js/pc/all-25e2d5bcab.js\"></script><script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\n"
			"<script type=\"text/javascript\" src=\"http://cdn.myanimelist.net/js/hover.js?v=54\"></script>\n"
			"<script type=\"text/javascript\" src=\"http://cdn.myanimelist.net/js/jquery.fancybox.pack.js?v=54\"></script>\n"
			"\n"
			"\n"
			"<script type=\"text/javascript\" src=\"http://cdn.myanimelist.net/js/profile.js?v=54\"></script>\n"
			"\n"
			"<script type=\"text/javascript\" src=\"http://cdn.myanimelist.net/js/myanimelist.js?v=54\" id=\"myanimelistjs\" data-myanimelistjs-params='{&quot;origin_url&quot;:&quot;http:\\/\\/myanimelist.net&quot;,&quot;is_request_bot_filter_log&quot;:true}'></script>\n"
			"\n"
			"\n"
			"\t<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.myanimelist.net/css/mal.ridlayout.css?v=31\" />\n"
			"\n"
			"<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.myanimelist.net/css/jquery.fancybox.css?v=31\" />\n"
			"<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.myanimelist.net/css/dialog.css?v=31\" />\n"
			"<link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.myanimelist.net/static/assets/css/pc/style-21aef74417.css\" />\n"
			"<link rel=\"search\" type=\"application/opensearchdescription+xml\" href=\"http://cdn.myanimelist.net/plugins/myanimelist.xml\" title=\"MyAnimeList\" />\n"
			"\n"
			"<link rel=\"shortcut icon\" href=\"http://cdn.myanimelist.net/images/faviconv5.ico\" />\n"
			"\n"
			"<!-- ### Load GPT Library ### -->\n"
			"<script type='text/javascript'>\n"
			"  var googletag = googletag || {};\n"
			"  googletag.cmd = googletag.cmd || [];\n"
			"  (function() {\n"
			"    var gads = document.createElement('script');\n"
			"    gads.async = true;\n"
			"    gads.type = 'text/javascript';\n"
			"    var useSSL = 'https:' == document.location.protocol;\n"
			"    gads.src = (useSSL ? 'https:' : 'http:') +\n"
			"               '//www.googletagservices.com/tag/js/gpt.js';\n"
			"    var node = document.getElementsByTagName('script')[0];\n"
			"    node.parentNode.insertBefore(gads, node);\n"
			"  })();\n"
			"</script>\n"
			"\n"
			"<script>\n"
			"  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n"
			"  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n"
			"  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n"
			"  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n"
			"\n"
			"  ga('create', 'UA-369102-1', 'auto');\n"
			"  ga('require', 'linkid'); // Enhanced Link Attribution\n"
			"  ga('send', 'pageview');\n"
			"\n"
			"</script>\n"
			"\n"
			"<script src=\"https://apis.google.com/js/platform.js\" async defer>{lang: 'en-GB'}</script>\n"
			"<script src=\"https://www.google.com/recaptcha/api.js?hl=en\"></script>\n"
			"\n"
			"  </head>\n"
			"\n"
			"    <body class=\"page-common profile\">  \n"
			"      <div id=\"myanimelist\">\n"
			"          <script type='text/javascript'>\n"
			"    googletag.cmd.push(function() {\n"
			"      googletag.defineOutOfPageSlot('/84947469/Skin_Others', 'div-gpt-ad-2058644762').addService(googletag.pubads());\n"
			"      googletag.pubads().collapseEmptyDivs();\n"
			"      googletag.enableServices();\n"
			"    });\n"
			"  </script>\n"
			"  <div style=\"display: none !important;\">\n"
			"    <div id='div-gpt-ad-2058644762'>\n"
			"      <script type='text/javascript'>\n"
			"        googletag.cmd.push(function() { googletag.display('div-gpt-ad-2058644762'); });\n"
			"      </script>\n"
			"    </div>\n"
			"  </div>\n"
			"\n"
			"    <script type='text/javascript'>\n"
			"    window.MAL.SkinAd.prepareForSkin('Skin_Others');\n"
			"  </script>\n"
			"\n"
			"    <div id=\"ad-skin-bg-left\" class=\"ad-skin-side-outer ad-skin-side-bg bg-left\">\n"
			"    <div id=\"ad-skin-left\" class=\"ad-skin-side left\" style=\"display: none;\">\n"
			"      <div id=\"ad-skin-left-absolute-block\">\n"
			"        <div id=\"ad-skin-left-fixed-block\"></div>\n"
			"      </div>\n"
			"    </div>\n"
			"  </div><div class=\"wrapper\">\n"
			"        \n"
			"                        \n"
			"        <div id=\"headerSmall\" >    <div id=\"header-menu\" class=\"pulldown\">\n"
			"    <div class=\"header-profile\">\n"
			"      <div class=\"header-notification js-header-notification\">\n"
			"\n"
			"  \n"
			"  \n"
			"  \n"
			"  \n"
			"\n"
			"  \n"
			"  \n"
			"  \n"
			"    \n"
			"</div>\n"
			"\n"
			"<script>\n"
			"window.MAL.headerNotification = {\"items\":[],\"countDigest\":0,\"dropdownOpenedAt\":0};\n"
			"window.MAL.headerNotification.templates = {\"root\":\"    <header-notification-button\\n      has-unread=\\\"{{hasUnreadItems}}\\\"\\n      has-new=\\\"{{hasNewItems}}\\\"\\n      is-dropdown-visible=\\\"{{isDropdownVisible}}\\\"\\n      on-click=\\\"{{toggleDropdown}}\\\">\\n    <\\/header-notification-button>\\n    <header-notification-dropdown\\n      items=\\\"{{items}}\\\"\\n      items-checked-in-this-session=\\\"{{itemsCheckedInThisSession}}\\\"\\n      num-whole-unread-items=\\\"{{numWholeUnreadItems}}\\\"\\n      dropdown-opened-at=\\\"{{dropdownOpenedAt}}\\\"\\n      is-visible=\\\"{{isDropdownVisible}}\\\"\\n      was-dropdown-closed=\\\"{{wasDropdownClosed}}\\\">\\n    <\\/header-notification-dropdown>\\n  \",\"button\":\"    <a class=\\\"header-notification-button\\\"\\n      v-class=\\\"'has-unread': hasUnread, new: hasNew\\\"\\n      v-on=\\\"\\n        click: onClick,\\n        keypress: onClick | key 'enter'\\n      \\\"\\n      v-attr=\\\"\\n        aria-expanded: isDropdownVisible ? 'true' : 'false'\\n      \\\"\\n      aria-haspopup=\\\"true\\\"\\n      aria-label=\\\"Notifications\\\"\\n      title=\\\"Notifications\\\"\\n      tabindex=\\\"0\\\">\\n      <i class=\\\"fa fa-bell\\\"><\\/i>\\n    <\\/a>\\n  \",\"dropdown\":\"    <div class=\\\"header-notification-dropdown\\\" v-show=\\\"isVisible\\\">\\n      <div class=\\\"arrow_box\\\">\\n        <div class=\\\"header-notification-dropdown-inner\\\">\\n          <h3>\\n            <span class=\\\"mark-all\\\"\\n              v-class=\\\"disabled: !hasUnreadItems\\\"\\n              v-on=\\\"click: checkAllItems\\\">\\n              <i class=\\\"fa fa-check mr4\\\"><\\/i>Mark All as Read\\n            <\\/span>\\n            Newest Notifications\\n          <\\/h3>\\n          <ol class=\\\"header-notification-item-list\\\">\\n            <li class=\\\"header-notification-item {{item.typeIdentifier}}\\\"\\n              v-class=\\\"new: isNewItem(item)\\\"\\n              v-repeat=\\\"item: items\\\">\\n              <a v-if=\\\"item.url\\\" v-on=\\\"click: checkItem(item)\\\" href=\\\"{{item.url}}\\\" class=\\\"background\\\"><\\/a>\\n              <div class=\\\"inner\\\"\\n                v-class=\\\"is-read: item.isRead && !isItemCheckedInThisSession(item)\\\">\\n                <div class=\\\"header-notification-item-header\\\">\\n                                    <span class=\\\"is-read\\\"\\n                    v-show=\\\"!item.isRead || isItemCheckedInThisSession(item)\\\"\\n                    v-class=\\\"checked: item.isRead\\\"\\n                    v-on=\\\"click: checkItem(item)\\\">\\n                    <i class=\\\"fa fa-check\\\"><\\/i>\\n                    <i class=\\\"fa fa-check-circle\\\"><\\/i>\\n                  <\\/span>\\n                                    <span class=\\\"time\\\">{{item.createdAtForDisplay}}<\\/span>\\n                                    <span class=\\\"category\\\">{{item.categoryName}}<\\/span>\\n                <\\/div>\\n                                <div class=\\\"header-notification-item-content {{item.typeIdentifier}}\\\">\\n                                    <component is=\\\"{{resolveComponent(item)}}\\\"\\n                    v-if=\\\"!item.isDeleted\\\" \\n                    item=\\\"{{item}}\\\"\\n                    on-check-item={{checkItem}}>\\n                  <\\/component>\\n                  <div class=\\\"deleted\\\" v-if=\\\"item.isDeleted\\\">(deleted)<\\/div>\\n                <\\/div>\\n              <\\/div>\\n            <\\/li>\\n            <li class=\\\"header-notification-item empty\\\" v-if=\\\"items.length === 0\\\">\\n              <p>No notifications.<\\/p>\\n            <\\/li>\\n          <\\/ol>\\n          <div class=\\\"header-notification-view-all\\\">\\n            <a href=\\\"http:\\/\\/myanimelist.net\\/notifications\\\">\\n              View All\\n              <span v-if=\\\"numWholeUnreadItems > 0\\\">\\n                ({{numWholeUnreadItems &lt; 100 ? numWholeUnreadItems : &quot;99+&quot;}})\\n              <\\/span>\\n            <\\/a>\\n          <\\/div>\\n        <\\/div>\\n      <\\/div>\\n    <\\/div>\\n  \",\"itemFriendRequest\":\"    <p>\\n      <a href=\\\"{{item.friendProfileUrl}}\\\" class=\\\"fl-l mr4\\\"><img v-attr=\\\"src: item.friendImageUrl\\\" alt=\\\"{{item.friendName}}\\\"><\\/a>\\n      <a href=\\\"{{item.friendProfileUrl}}\\\">{{item.friendName}}<\\/a>\\n      sent you a friend request{{ item.message.length ? \\\":\\\" : \\\".\\\" }}\\n      <q class=\\\"message\\\" v-if=\\\"item.message.length\\\">{{item.message}}<\\/q>\\n    <\\/p>\\n    <p class=\\\"actions mt8\\\">\\n      <span v-if=\\\"!item.isApproved\\\">\\n        <span class=\\\"action-button accept\\\" v-on=\\\"click: accept\\\">Accept<\\/span><span class=\\\"action-button deny\\\" v-on=\\\"click: deny\\\">Deny<\\/span>      <\\/span>\\n      <span v-if=\\\"item.isApproved\\\">\\n        <span class=\\\"result\\\">Accepted<\\/span>\\n      <\\/span>\\n    <\\/p>\\n  \",\"itemProfileComment\":\"    <a href=\\\"{{item.commentUserProfileUrl}}\\\">{{item.commentUserName}}<\\/a>\\n    posted a comment on your profile{{ item.text.length ? \\\":\\\" : \\\".\\\" }}\\n    <q class=\\\"message\\\" v-if=\\\"item.text.length\\\">{{item.text}}<\\/q>\\n  \",\"itemForumQuote\":\"    <a href=\\\"{{item.quoteUserProfileUrl}}\\\">{{item.quoteUserName}}<\\/a>\\n    quoted your post in the <a href=\\\"{{item.topicUrl}}\\\">{{item.topicTitle}}<\\/a> thread.\\n  \",\"itemUserMentions\":\"    <a href=\\\"{{item.senderProfileUrl}}\\\">{{item.senderName}}<\\/a>\\n    has mentioned your name in the\\n    <a href=\\\"{{item.pageUrl}}\\\">{{item.pageTitle}}<\\/a>\\n    <span v-text=\\\"{\\n      user_mention_in_forum_message: 'thread'\\n    }[item.typeIdentifier]\\\"><\\/span>.\\n  \"};\n"
			"</script>\n"
			"<div class=\"border\"></div>\n"
			"      <a class=\"profile-image\" style=\"background-image:url(http://cdn.myanimelist.net/images/userimages/4449926.jpg)\" href=\"/profile/arkenthera\"></a>\n"
			"      <span class=\"profile-name\">arkenthera</span>\n"
			"    </div>\n"
			"    <div id=\"header-menu-profile-container\">\n"
			"      <ul id=\"header-menu-profile\" class=\"header-menu-profile\">\n"
			"        <li><a href=\"/profile/arkenthera\">Profile</a></li>\n"
			"        <li><a href=\"/editprofile.php?go=myoptions\">Settings</a></li>\n"
			"        <li><form action=\"http://myanimelist.net/logout.php\" method=\"post\">\n"
			"  <a href=\"javascript:void(0);\" onclick=\"$(this).parent().submit();\">\n"
			"    Logout\n"
			"  </a>\n"
			"</form>\n"
			"</li>\n"
			"      </ul>\n"
			"    </div>\n"
			"  </div>\n"
			"<a href=\"/panel.php\">MyAnimeList.net</a>\n"
			"                  </div>\n"
			"        \n"
			"                \n"
			"          <div id=\"menu\">\n"
			"\n"
			"    <div id=\"menu_right\"><form id=\"searchBar\" method=\"get\" class=\"searchBar\"><div class=\"form-select-outer fl-l\"><select name=\"type\" id=\"topSearchValue\" class=\"inputtext\"><option value=\"anime\">Anime</option><option value=\"manga\">Manga</option><option value=\"character\">Characters</option><option value=\"person\">People</option><option value=\"club\">Clubs</option><option value=\"user\">Users</option></select></div><input id=\"topSearchText\" type=\"text\" name=\"keyword\" class=\"inputtext js-topSearchText fl-l\" placeholder=\"Search Anime, Manga, and more...\" size=\"30\" autocomplete=\"off\" /><input id=\"topSearchButon\" class=\"fl-l\" type=\"submit\" value=\"&#xf002\"></form><div id=\"topSearchResultList\" class=\"incrementalSearchResultList\"></div></div>\n"
			"    <div id=\"menu_left\">\n"
			"                        <ul id=\"nav\">\n"
			"              <li class=\"medium\">\n"
			"  <a href=\"#\" class=\"non-link\">My Page</a><ul class=\"wider\"><li><span class=\"edit\"><a href=\"/editprofile.php\">Edit</a></span><a href=\"/profile/arkenthera\">Profile</a></li><li><a href=\"/mymessages.php\">Messages</a></li><li><a href=\"/myfriends.php\">Friends</a></li><li><a href=\"/clubs.php?action=myclubs\">Clubs</a></li><li><span class=\"edit\"><a href=\"/myblog.php\">Edit</a></span><a href=\"/blog/arkenthera\">Blog</a></li><li><a href=\"/myreviews.php\">Reviews</a></li><li><a href=\"/myrecommendations.php\">Recommendations</a></li><li><form action=\"http://myanimelist.net/logout.php\" method=\"post\"><a href=\"javascript:void(0);\" onclick=\"$(this).parent().submit();\">\n"
			"    Logout\n"
			"  </a></form></li></ul>  <li class=\"small\"><a href=\"#\" class=\"non-link\">Anime</a>\n"
			"    <ul class=\"wider\">\n"
			"            <li><a href=\"/animelist/arkenthera\">View List</a></li>\n"
			"      <li><a href=\"/addtolist.php\">Quick Add Anime</a></li>\n"
			"            <li><a href=\"/anime.php\">Anime Search</a></li>\n"
			"      <li><a href=\"/reviews.php?t=anime\">Reviews</a></li>\n"
			"      <li><a href=\"/recommendations.php?s=recentrecs&t=anime\">Recommendations</a></li>\n"
			"      <li><a href=\"/topanime.php\">Top Anime</a></li>\n"
			"      <li><a href=\"http://myanimelist.net/anime/season\">Seasonal Anime</a></li>\n"
			"    </ul>\n"
			"  </li>\n"
			"  <li class=\"small\"><a href=\"#\" class=\"non-link\">Manga</a>\n"
			"    <ul class=\"wider\">\n"
			"            <li><a href=\"/mangalist/arkenthera\">View List</a></li>\n"
			"      <li><a href=\"/addtolist.php\">Quick Add Manga</a></li>\n"
			"            <li><a href=\"/manga.php\">Manga Search</a></li>\n"
			"      <li><a href=\"/reviews.php?t=manga\">Reviews</a></li>\n"
			"      <li><a href=\"/recommendations.php?s=recentrecs&t=manga\">Recommendations</a></li>\n"
			"      <li><a href=\"/topmanga.php\">Top Manga</a></li>\n"
			"    </ul>\n"
			"  </li>\n"
			"  <li><a href=\"#\" class=\"non-link\">Community</a>\n"
			"    <ul>\n"
			"      <li><a href=\"/forum/\">Forums</a></li>\n"
			"      <li><a href=\"/clubs.php\">Clubs</a></li>\n"
			"      <li><a href=\"/blog.php\">Blogs</a></li>\n"
			"      <li><a href=\"/users.php\">Users</a></li>\n"
			"    </ul>\n"
			"  </li>\n"
			"  <li class=\"small2\"><a href=\"#\" class=\"non-link\">Industry</a>\n"
			"    <ul class=\"wider\">\n"
			"      <li><a href=\"/news\">News</a></li>\n"
			"      <li><a href=\"http://myanimelist.net/featured\">Featured Articles</a></li>\n"
			"      <li><a href=\"/people.php\">People</a></li>\n"
			"      <li><a href=\"/character.php\">Characters</a></li>\n"
			"    </ul>\n"
			"  </li>\n"
			"  <li class=\"small\"><a href=\"#\" class=\"non-link\">Watch</a>\n"
			"    <ul class=\"wider\">\n"
			"      <li><a href=\"/watch\">Promotional Videos</a></li>\n"
			"      <li><a href=\"/watch/daisuki\">DAISUKI</a></li>\n"
			"    </ul>\n"
			"  </li>\n"
			"  <li class=\"smaller\"><a href=\"#\" class=\"non-link\">Help</a>\n"
			"    <ul class=\"wide\">\n"
			"      <li><a href=\"/about.php\">About</a></li>\n"
			"      <li><a href=\"/about.php?go=support\">Support</a></li>\n"
			"      <li><a href=\"/about.php?go=advertising\">Advertising</a></li>\n"
			"      <li><a href=\"/forum/?topicid=515949\">FAQ</a></li>\n"
			"      <li><a href=\"/modules.php?go=report\">Report</a></li>\n"
			"      <li><a href=\"/about.php?go=team\">Staff</a></li>\n"
			"    </ul>\n"
			"  </li>\n"
			"  </ul>\n"
			"                  </div>\n"
			"  </div>        <div id=\"contentWrapper\" >\n"
			"          <div>\n"
			"                                        <h1 class=\"h1\">\n"
			"                  <a class=\"header-right mt4 mr0\" href=\"http://myanimelist.net/editprofile.php\"><i class=\"fa fa-cog mr4\"></i>Edit Profile</a><span class=\"di-ib po-r\">\n"
			"  arkenthera's Profile</span>              </h1>\n"
			"                      </div>\n"
			"          <div id=\"content\">\n"
			"\n"
			"  \n"
			"  <div class=\"content-container\">\n"
			"        <div class=\"container-left\">\n"
			"      \n"
			"<div class=\"user-profile\">\n"
			"\n"
			"  <div class=\"user-image mb8\">\n"
			"          <img src=\"http://cdn.myanimelist.net/images/userimages/4449926.jpg\">\n"
			"      </div>\n"
			"\n"
			"  \n"
			"  <div class=\"user-function mb8\">\n"
			"    <a href=\"http://myanimelist.net/profile/arkenthera#lastcomment\" title=\"Comments of arkenthera's Profile\" class=\"icon-user-function icon-comment js-user-function\" id=\"comment\"><span class=\"text\">Comment</span></a><span class=\"icon-user-function icon-message js-user-function disabled\" id=\"message\"><span class=\"text\">Message</span></span><span class=\"icon-user-function icon-request js-user-function disabled\" id=\"request\"><span class=\"text\">Request</span></span>  </div>\n"
			"\n"
			"  <ul class=\"user-status border-top pb8 mb4\">\n"
			"    <li class=\"clearfix\"><span class=\"user-status-title di-ib fl-l fw-b\">Last Online</span><span class=\"user-status-data di-ib fl-r online\">Now</span></li><li class=\"clearfix\"><span class=\"user-status-title di-ib fl-l fw-b\">Gender</span><span class=\"user-status-data di-ib fl-r\">Male</span></li><li class=\"clearfix\"><span class=\"user-status-title di-ib fl-l fw-b\">Birthday</span><span class=\"user-status-data di-ib fl-r\">Jan 1, 1994</span></li><li class=\"clearfix\"><span class=\"user-status-title di-ib fl-l fw-b\">Joined</span><span class=\"user-status-data di-ib fl-r\">Jan 31, 2015</span></li>  </ul>\n"
			"\n"
			"  <div class=\"user-button clearfix mb12\">\n"
			"    <a class=\"btn-profile-submit fl-l\" href=\"http://myanimelist.net/animelist/arkenthera\">Anime List</a>\n"
			"    <a class=\"btn-profile-submit fl-r\" href=\"http://myanimelist.net/mangalist/arkenthera\">Manga List</a>\n"
			"  </div>\n"
			"\n"
			"  <ul class=\"user-status border-top\">\n"
			"    <li class=\"icon-statistics link\"><a href=\"http://myanimelist.net/profile/arkenthera#statistics\" class=\"di-b\"><span class=\"user-status-title di-ib fw-b\">Statistics</span></a></li><li class=\"icon-history link\"><a href=\"http://myanimelist.net/history/arkenthera\"><span class=\"user-status-title di-ib fw-b w100\">History</span></a></li>  </ul>\n"
			"\n"
			"  <ul class=\"user-status border-top mt12 mb12\">\n"
			"    <li class=\"link\"><a href=\"http://myanimelist.net/forum/index.php?action=search&amp;u=arkenthera&amp;q=&amp;uloc=1&amp;loc=-1\" class=\"clearfix\"><span class=\"user-status-title di-ib fl-l fw-b\">Forum Posts</span><span class=\"user-status-data di-ib fl-r fw-b\">5</span></a></li><li class=\"link\"><a href=\"http://myanimelist.net/profile/arkenthera/reviews\" class=\"clearfix\" rel=\"nofollow\"><span class=\"user-status-title di-ib fl-l fw-b\">Reviews</span><span class=\"user-status-data di-ib fl-r fw-b\">0</span></a></li><li class=\"clearfix link\"><a href=\"http://myanimelist.net/profile/arkenthera/recommendations\" class=\"clearfix\" rel=\"nofollow\"><span class=\"user-status-title di-ib fl-l fw-b\">Recommendations</span><span class=\"user-status-data di-ib fl-r fw-b\">0</span></a></li><li class=\"clearfix link\"><a href=\"http://myanimelist.net/blog/arkenthera\" class=\"clearfix\" rel=\"nofollow\"><span class=\"user-status-title di-ib fl-l fw-b\">Blog Posts</span><span class=\"user-status-data di-ib fl-r fw-b\">0</span></a></li><li class=\"clearfix link\"><a href=\"http://myanimelist.net/profile/arkenthera/clubs\" class=\"clearfix\" rel=\"nofollow\"><span class=\"user-status-title di-ib fl-l fw-b\">Clubs</span><span class=\"user-status-data di-ib fl-r fw-b\">0</span></a></li>  </ul>\n"
			"\n"
			"  \n"
			"  \n"
			"  <h4><a href=\"http://myanimelist.net/profile/arkenthera/friends\" class=\"fl-r fs11 fw-n ff-Verdana\">All (2)</a>Friends</h4>\n"
			"  <div class=\"user-friends pt4 pb12\">\n"
			"    <a href=\"http://myanimelist.net/profile/julesawdupin\" class=\"icon-friend\" style=\"background-image:url('http://cdn.myanimelist.net/r/76x120/images/userimages/3974951.jpg?s=c753a7310eec40b9863df1a44cf50330')\" title=\"julesawdupin\">julesawdupin</a><a href=\"http://myanimelist.net/profile/LostInTheAbyss\" class=\"icon-friend\" style=\"background-image:url('http://cdn.myanimelist.net/r/76x120/images/userimages/4496454.jpg?s=b650919f336f2cd24c1fa78baea7e4ea')\" title=\"LostInTheAbyss\">LostInTheAbyss</a>  </div>\n"
			"\n"
			"      <h4>Also Available at</h4>\n"
			"    <div class=\"user-profile-sns\">\n"
			"      <a href=\"http://arkenthera.github.io\" target=\"_blank\" class=\"icon-profile-sns icon-url ww-bw\">arkenthera.github.io</a><br>    </div>\n"
			"  \n"
			"  <h4 class=\"icon-rss\">RSS Feeds</h4>\n"
			"  <div class=\"user-profile-sns\">\n"
			"    <a class=\"di-ib mb8\" href=\"http://myanimelist.net/rss.php?type=rw&amp;u=arkenthera\" rel=\"nofollow\">Recent Anime</a><br><a class=\"di-ib mb8\" href=\"http://myanimelist.net/rss.php?type=rwe&amp;u=arkenthera\" rel=\"nofollow\">Recent Anime by Episode</a><br><a class=\"di-ib mb8\" href=\"http://myanimelist.net/rss.php?type=rm&amp;u=arkenthera\" rel=\"nofollow\">Recent Manga</a><br><a class=\"di-ib mb8\" href=\"http://myanimelist.net/rss.php?type=rrm&amp;u=arkenthera\" rel=\"nofollow\">Recent Manga by Chapter</a><br><a class=\"di-ib mb8\" href=\"http://myanimelist.net/rss.php?type=blog&amp;id=4449926\" rel=\"nofollow\">Blog Feed</a><br>  </div>\n"
			"\n"
			"</div>\n"
			"    </div>\n"
			"\n"
			"        <div class=\"container-right\">\n"
			"              <div class=\"user-profile-about js-truncate-outer\">\n"
			"          <div class=\"profile-about-user js-truncate-inner\">\n"
			"                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"table-layout: fixed\"><tr><td>\n"
			"              <div class=\"word-break\">\n"
			"                <div style=\"text-align: center;\"><span style=\"font-size: 250%;\"><span style=\"color: black\">(✿ ◕‿◕)</span> <span style=\"color: blue\"><b>DAMN THIS PROFILE IS FANCY </b></span> <span style=\"color: black\">(✿ ◕‿◕)</span></span></div><br />\n"
			"<img class=\"userimg\" src=\"http://i.imgur.com/spRNrrJ.jpg\" /><br />\n"
			"<br />\n"
			"\n"
			"              <div>\n"
			"            </td></tr></table>\n"
			"          </div>\n"
			"        </div>\n"
			"      \n"
			"            <div class=\"user-statistics mb24\" id=\"statistics\">\n"
			"        <h2>Statistics</h2>\n"
			"\n"
			"                <div class=\"user-statistics-stats mt16\">\n"
			"                    <div class=\"stats anime\">\n"
			"                        <h5>Anime Stats</h5>\n"
			"\n"
			"                                    \n"
			"            <div class=\"stat-score di-t w100 pt8\">\n"
			"              <div class=\"di-tc al pl8 fs12 fw-b\"><span class=\"fn-grey2 fw-n\">Days: </span>24.6</div>\n"
			"              <div class=\"di-tc ar pr8 fs12 fw-b\"><span class=\"fn-grey2 fw-n\">Mean Score: </span>8.19</div>\n"
			"            </div>\n"
			"\n"
			"            <div class=\"stats-graph mt8\"><span class=\"graph watching\" style=\"width: 15.049504950495px\"></span><span class=\"graph completed\" style=\"width: 212.57425742574px\"></span><span class=\"graph on-hold\" style=\"width: 20.693069306931px\"></span><span class=\"graph dropped\" style=\"width: 9.4059405940594px\"></span><span class=\"graph plantowatch\" style=\"width: 122.27722772277px\"></span></div>\n"
			"            <div class=\"mt12 ml8 mr8 clearfix\">\n"
			"              <ul class=\"stats-status fl-l\"><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/animelist/arkenthera?status=1\" class=\"di-ib fl-l lh10 circle watching\">Watching</a><span class=\"di-ib fl-r lh10\">8</span></li><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/animelist/arkenthera?status=2\" class=\"di-ib fl-l lh10 circle completed\">Completed</a><span class=\"di-ib fl-r lh10\">113</span></li><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/animelist/arkenthera?status=3\" class=\"di-ib fl-l lh10 circle on-hold\">On-Hold</a><span class=\"di-ib fl-r lh10\">11</span></li><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/animelist/arkenthera?status=4\" class=\"di-ib fl-l lh10 circle dropped\">Dropped</a><span class=\"di-ib fl-r lh10\">5</span></li><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/animelist/arkenthera?status=6\" class=\"di-ib fl-l lh10 circle plantowatch\">Plan to Watch</a><span class=\"di-ib fl-r lh10\">65</span></li></ul><ul class=\"stats-data fl-r\"><li class=\"clearfix mb12\"><span class=\"di-ib fl-l fn-grey2\">Total Entries</span><span class=\"di-ib fl-r\">202</span></li><li class=\"clearfix mb12\"><span class=\"di-ib fl-l fn-grey2\">Rewatched</span><span class=\"di-ib fl-r\">0</span></li><li class=\"clearfix mb12\"><span class=\"di-ib fl-l fn-grey2\">Episodes</span><span class=\"di-ib fl-r\">1,501</span></li></ul>            </div>\n"
			"          </div>\n"
			"\n"
			"                    <div class=\"updates anime\">\n"
			"            <h5 class=\"mb12\">\n"
			"              <a class=\"floatRightHeader ff-Verdana\" href=\"http://myanimelist.net/history/arkenthera/anime\">Anime History</a>\n"
			"              Last Anime Updates\n"
			"            </h5>\n"
			"                            \n"
			"<div class=\"statistics-updates di-b w100 mb8\">\n"
			"  <a href=\"http://myanimelist.net/anime/6213/Toaru_Kagaku_no_Railgun\" class=\"fl-l di-ib mr8 image\">\n"
			"    <img src=\"http://cdn.myanimelist.net/r/80x120/images/anime/8/53581.jpg?s=75151d37121db3840bf857b7305ae9c7\" width=\"40\" alt=\"Toaru Kagaku no Railgun\">\n"
			"  </a>\n"
			"\n"
			"                  \n"
			"  <div class=\"data\">\n"
			"    <a href=\"http://myanimelist.net/anime/6213/Toaru_Kagaku_no_Railgun\">Toaru Kagaku no Railgun</a>\n"
			"    <div class=\"clearfix graph-content pt8\">\n"
			"      <span class=\"fl-r fn-grey2\">Today, 1:33 AM</span>\n"
			"      <div class=\"graph fl-l\"><span class=\"graph-inner watching\" style=\"width:143px\"></span></div>\n"
			"    </div>\n"
			"\n"
			"    <div class=\"fn-grey2\">\n"
			"            Watching\n"
			"              <span class=\"text watching\">18</span>/24\n"
			"            &middot;             Scored\n"
			"      -</div>\n"
			"  </div>\n"
			"</div>\n"
			"                \n"
			"<div class=\"statistics-updates di-b w100 mb8\">\n"
			"  <a href=\"http://myanimelist.net/anime/28391/Ao_no_Kanata_no_Four_Rhythm\" class=\"fl-l di-ib mr8 image\">\n"
			"    <img src=\"http://cdn.myanimelist.net/r/80x120/images/anime/9/77839.jpg?s=57f0f38cb30dd679ad37274066612a25\" width=\"40\" alt=\"Ao no Kanata no Four Rhythm\">\n"
			"  </a>\n"
			"\n"
			"                  \n"
			"  <div class=\"data\">\n"
			"    <a href=\"http://myanimelist.net/anime/28391/Ao_no_Kanata_no_Four_Rhythm\">Ao no Kanata no Four Rhythm</a>\n"
			"    <div class=\"clearfix graph-content pt8\">\n"
			"      <span class=\"fl-r fn-grey2\">Yesterday, 9:35 PM</span>\n"
			"      <div class=\"graph fl-l\"><span class=\"graph-inner watching\" style=\"width:48px\"></span></div>\n"
			"    </div>\n"
			"\n"
			"    <div class=\"fn-grey2\">\n"
			"            Watching\n"
			"              <span class=\"text watching\">3</span>/12\n"
			"            &middot;             Scored\n"
			"      -</div>\n"
			"  </div>\n"
			"</div>\n"
			"                \n"
			"<div class=\"statistics-updates di-b w100 mb8\">\n"
			"  <a href=\"http://myanimelist.net/anime/31414/Nijiiro_Days\" class=\"fl-l di-ib mr8 image\">\n"
			"    <img src=\"http://cdn.myanimelist.net/r/80x120/images/anime/8/76691.jpg?s=e2310974bfe52282944b5eef5ec5424c\" width=\"40\" alt=\"Nijiiro Days\">\n"
			"  </a>\n"
			"\n"
			"                  \n"
			"  <div class=\"data\">\n"
			"    <a href=\"http://myanimelist.net/anime/31414/Nijiiro_Days\">Nijiiro Days</a>\n"
			"    <div class=\"clearfix graph-content pt8\">\n"
			"      <span class=\"fl-r fn-grey2\">Jan 25, 10:33 PM</span>\n"
			"      <div class=\"graph fl-l\"><span class=\"graph-inner watching\" style=\"width:24px\"></span></div>\n"
			"    </div>\n"
			"\n"
			"    <div class=\"fn-grey2\">\n"
			"            Watching\n"
			"              <span class=\"text watching\">3</span>/24\n"
			"            &middot;             Scored\n"
			"      -</div>\n"
			"  </div>\n"
			"</div>\n"
			"          </div>\n"
			"        </div>\n"
			"\n"
			"                <div class=\"user-statistics-stats mt16\">\n"
			"                    <div class=\"stats manga\">\n"
			"            <h5>Manga Stats</h5>\n"
			"\n"
			"                                    \n"
			"                        <div class=\"stat-score di-t w100 pt8 mb8\">\n"
			"              <div class=\"di-tc al pl8 fs12 fw-b\"><span class=\"fn-grey2 fw-n\">Days: </span>10.0</div>\n"
			"              <div class=\"di-tc ar pr8 fs12 fw-b\"><span class=\"fn-grey2 fw-n\">Mean Score: </span>8.14</div>\n"
			"            </div>\n"
			"\n"
			"            <div class=\"stats-graph mt8\"><span class=\"graph reading\" style=\"width: 88.372093023256px\"></span><span class=\"graph completed\" style=\"width: 159.06976744186px\"></span><span class=\"graph on-hold\" style=\"width: 17.674418604651px\"></span><span class=\"graph dropped\" style=\"width: 0px\"></span><span class=\"graph plantoread\" style=\"width: 114.88372093023px\"></span></div>\n"
			"            <div class=\"mt12 ml8 mr8 clearfix\">\n"
			"              <ul class=\"stats-status fl-l\"><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/mangalist/arkenthera?status=1\" class=\"di-ib fl-l lh10 circle reading\">Reading</a><span class=\"di-ib fl-r lh10\">10</span></li><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/mangalist/arkenthera?status=2\" class=\"di-ib fl-l lh10 circle completed\">Completed</a><span class=\"di-ib fl-r lh10\">18</span></li><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/mangalist/arkenthera?status=3\" class=\"di-ib fl-l lh10 circle on-hold\">On-Hold</a><span class=\"di-ib fl-r lh10\">2</span></li><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/mangalist/arkenthera?status=4\" class=\"di-ib fl-l lh10 circle dropped\">Dropped</a><span class=\"di-ib fl-r lh10\">0</span></li><li class=\"clearfix mb12\"><a href=\"http://myanimelist.net/mangalist/arkenthera?status=6\" class=\"di-ib fl-l lh10 circle plantoread\">Plan to Read</a><span class=\"di-ib fl-r lh10\">13</span></li></ul><ul class=\"stats-data fl-r\"><li class=\"clearfix mb12\"><span class=\"di-ib fl-l fn-grey2\">Total Entries</span><span class=\"di-ib fl-r\">43</span></li><li class=\"clearfix mb12\"><span class=\"di-ib fl-l fn-grey2\">Reread</span><span class=\"di-ib fl-r\">0</span></li><li class=\"clearfix mb12\"><span class=\"di-ib fl-l fn-grey2\">Chapters</span><span class=\"di-ib fl-r\">1,803</span></li><li class=\"clearfix mb12\"><span class=\"di-ib fl-l fn-grey2\">Volumes</span><span class=\"di-ib fl-r\">137</span></li></ul>            </div>\n"
			"          </div>\n"
			"\n"
			"                    <div class=\"updates manga\">\n"
			"            <h5 class=\"mb12\">\n"
			"              <a class=\"floatRightHeader ff-Verdana\" href=\"http://myanimelist.net/history/arkenthera/manga\">Manga History</a>\n"
			"              Last Manga Updates\n"
			"            </h5>\n"
			"                            \n"
			"<div class=\"statistics-updates di-b w100 mb8\">\n"
			"  <a href=\"http://myanimelist.net/manga/45757/Shokugeki_no_Souma\" class=\"fl-l di-ib mr8 image\">\n"
			"    <img src=\"http://cdn.myanimelist.net/r/80x120/images/manga/1/115803.jpg?s=beec18f3429079d28cab4feb06301972\" width=\"40\" alt=\"Shokugeki no Souma\">\n"
			"  </a>\n"
			"\n"
			"          \n"
			"  <div class=\"data\">\n"
			"    <a href=\"http://myanimelist.net/manga/45757/Shokugeki_no_Souma\">Shokugeki no Souma</a>\n"
			"    <div class=\"clearfix graph-content pt8\">\n"
			"      <span class=\"fl-r fn-grey2\">Oct 22, 2015 7:18 AM</span>\n"
			"      <div class=\"graph fl-l\"><span class=\"graph-inner reading\" style=\"width:95px\"></span></div>\n"
			"    </div>\n"
			"\n"
			"    <div class=\"fn-grey2\">\n"
			"            Reading\n"
			"              <span class=\"text reading\">139</span>/-\n"
			"            &middot;             Scored\n"
			"      -</div>\n"
			"  </div>\n"
			"</div>\n"
			"                \n"
			"<div class=\"statistics-updates di-b w100 mb8\">\n"
			"  <a href=\"http://myanimelist.net/manga/35003/Yamada-kun_to_7-nin_no_Majo\" class=\"fl-l di-ib mr8 image\">\n"
			"    <img src=\"http://cdn.myanimelist.net/r/80x120/images/manga/3/82656.jpg?s=7a23fc7d6e8c16bac01ecae224b673ed\" width=\"40\" alt=\"Yamada-kun to 7-nin no Majo\">\n"
			"  </a>\n"
			"\n"
			"          \n"
			"  <div class=\"data\">\n"
			"    <a href=\"http://myanimelist.net/manga/35003/Yamada-kun_to_7-nin_no_Majo\">Yamada-kun to 7-nin no Majo</a>\n"
			"    <div class=\"clearfix graph-content pt8\">\n"
			"      <span class=\"fl-r fn-grey2\">Oct 13, 2015 5:43 PM</span>\n"
			"      <div class=\"graph fl-l\"><span class=\"graph-inner on-hold\" style=\"width:95px\"></span></div>\n"
			"    </div>\n"
			"\n"
			"    <div class=\"fn-grey2\">\n"
			"            On-Hold\n"
			"              <span class=\"text on-hold\">132</span>/-\n"
			"            &middot;             Scored\n"
			"      -</div>\n"
			"  </div>\n"
			"</div>\n"
			"                \n"
			"<div class=\"statistics-updates di-b w100 mb8\">\n"
			"  <a href=\"http://myanimelist.net/manga/18939/Yasashii_Sekai_no_Tsukurikata\" class=\"fl-l di-ib mr8 image\">\n"
			"    <img src=\"http://cdn.myanimelist.net/r/80x120/images/manga/2/144217.jpg?s=aaf939768acf3d2f8e6c8b7d3d53a834\" width=\"40\" alt=\"Yasashii Sekai no Tsukurikata\">\n"
			"  </a>\n"
			"\n"
			"                  \n"
			"  <div class=\"data\">\n"
			"    <a href=\"http://myanimelist.net/manga/18939/Yasashii_Sekai_no_Tsukurikata\">Yasashii Sekai no Tsukurikata</a>\n"
			"    <div class=\"clearfix graph-content pt8\">\n"
			"      <span class=\"fl-r fn-grey2\">Oct 6, 2015 5:24 PM</span>\n"
			"      <div class=\"graph fl-l\"><span class=\"graph-inner reading\" style=\"width:144px\"></span></div>\n"
			"    </div>\n"
			"\n"
			"    <div class=\"fn-grey2\">\n"
			"            Reading\n"
			"              <span class=\"text reading\">28</span>/37\n"
			"            &middot;             Scored\n"
			"      -</div>\n"
			"  </div>\n"
			"</div>\n"
			"          </div>\n"
			"        </div>\n"
			"      </div>\n"
			"\n"
			"\n"
			"      <h2 class=\"mb12\">\n"
			"                  <a href=\"http://myanimelist.net/editprofile.php?go=favorites\" class=\"floatRightHeader ff-Verdana\">Edit</a>\n"
			"                Favorites\n"
			"      </h2>\n"
			"      <div class=\"user-favorites-outer js-truncate-outer\">\n"
			"      <div class=\"user-favorites js-truncate-inner di-t mb24\">\n"
			"        <div class=\"di-tc\">\n"
			"          <h5 class=\"mb8 mr8\">Anime</h5>\n"
			"                      <ul class=\"favorites-list anime\">\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/anime/5081/Bakemonogatari\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/anime/11/75274.jpg?s=598c1f6246110588b9e0f9909863c4ec')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/anime/5081/Bakemonogatari\">Bakemonogatari</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          TV\n"
			"                    &middot; 2009\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/anime/10620/Mirai_Nikki_TV\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/anime/13/33465.jpg?s=ac5c89074a2064a2d56de3ba306d0b61')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/anime/10620/Mirai_Nikki_TV\">Mirai Nikki (TV)</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          TV\n"
			"                    &middot; 2011\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/anime/23273/Shigatsu_wa_Kimi_no_Uso\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/anime/3/67177.jpg?s=83ad9e6379f1f0db5dd1e3a947c6d422')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/anime/23273/Shigatsu_wa_Kimi_no_Uso\">Shigatsu wa Kimi no Uso</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          TV\n"
			"                    &middot; 2014\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/anime/12189/Hyouka\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/anime/13/50521.jpg?s=087e0b7f5c8b55710e8efd1925b6a332')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/anime/12189/Hyouka\">Hyouka</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          TV\n"
			"                    &middot; 2012\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/anime/27989/Hibike_Euphonium\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/anime/6/72445.jpg?s=b1603d3ec07881c8c14b1429150efe55')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/anime/27989/Hibike_Euphonium\">Hibike! Euphonium</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          TV\n"
			"                    &middot; 2015\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                          </ul>\n"
			"                  </div>\n"
			"\n"
			"        <div class=\"di-tc\">\n"
			"          <h5 class=\"mb8 mr8\">Manga</h5>\n"
			"                      <ul class=\"favorites-list manga\">\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/manga/11734/Watashitachi_no_Shiawase_na_Jikan\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/manga/3/66993.jpg?s=b1e06819513f208e641457511b1ad1eb')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/manga/11734/Watashitachi_no_Shiawase_na_Jikan\">Watashitachi no Shiawase na Jikan</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          Manga\n"
			"                    &middot; 2008\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/manga/24294/Ao_Haru_Ride\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/manga/1/62369.jpg?s=3e17df58dac9c868b931bf3f7761f428')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/manga/24294/Ao_Haru_Ride\">Ao Haru Ride</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          Manga\n"
			"                    &middot; 2011\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/manga/37707/Shigatsu_wa_Kimi_no_Uso\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/manga/3/102691.jpg?s=0665f9c886330dbe9b7c44b29ac7dce5')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/manga/37707/Shigatsu_wa_Kimi_no_Uso\">Shigatsu wa Kimi no Uso</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          Manga\n"
			"                    &middot; 2011\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/manga/46282/Chikan_Otoko\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/manga/4/155148.jpg?s=f625a8198889e3d4d73eebe8566d20f4')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/manga/46282/Chikan_Otoko\">Chikan Otoko</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          Manga\n"
			"                    &middot; 2004\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/manga/50145/Citrus\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/manga/1/96903.jpg?s=92b4fde2280c98985ae5f792bb1c2167')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/manga/50145/Citrus\">Citrus</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                          Manga\n"
			"                    &middot; 2012\n"
			"                      </span>\n"
			"  </div>\n"
			"</li>\n"
			"                          </ul>\n"
			"                  </div>\n"
			"\n"
			"        <div class=\"di-tc\">\n"
			"          <h5 class=\"mb8 mr8\">Characters</h5>\n"
			"                      <ul class=\"favorites-list characters\">\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/character/4963/Yuno_Gasai\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/characters/2/280586.jpg?s=04d070c4ef9136b02d2bd00cd5314415')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/character/4963/Yuno_Gasai\">Gasai, Yuno</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                                                <a href=\"/anime/8460/Mirai_Nikki\" class=\"fn-grey2\">\n"
			"                        Mirai Nikki\n"
			"                      </a>\n"
			"                                          </span>\n"
			"  </div>\n"
			"</li>\n"
			"                                              <li class=\"list di-t mb8\">\n"
			"  <div class=\"di-tc\">\n"
			"    <a class=\"image\" href=\"http://myanimelist.net/character/22037/Hitagi_Senjougahara\" style=\"background-image:url('http://cdn.myanimelist.net/r/80x120/images/characters/11/287902.jpg?s=c64c0b19a1351d807dafa4580b59c979')\"></a>\n"
			"  </div>\n"
			"  <div class=\"di-tc va-t pl8 data\">\n"
			"    <a href=\"http://myanimelist.net/character/22037/Hitagi_Senjougahara\">Senjougahara, Hitagi</a><br>\n"
			"    <span class=\"di-ib mt4 fn-grey2\">\n"
			"                                                <a href=\"/anime/5081/Bakemonogatari\" class=\"fn-grey2\">\n"
			"                        Bakemonogatari\n"
			"                      </a>\n"
			"                                          </span>\n"
			"  </div>\n"
			"</li>\n"
			"                          </ul>\n"
			"                  </div>\n"
			"\n"
			"        <div class=\"di-tc\">\n"
			"          <h5 class=\"mb8\">People</h5>\n"
			"                      <p class=\"favorites-list\">No favorite people yet.</p>\n"
			"                  </div>\n"
			"      </div>\n"
			"      </div>\n"
			"\n"
			"\n"
			"                        <div class=\"user-comments mt24 pt24\" id=\"lastcomment\">\n"
			"        <h2>\n"
			"                      <span class=\"floatRightHeader ff-Verdana\">\n"
			"                            <a href=\"http://myanimelist.net/comments.php?id=4449926\">All Comments (2)</a>\n"
			"            </span>\n"
			"                    Comments\n"
			"        </h2>\n"
			"\n"
			"                            <div class=\"comment-form mt12 mb24\">\n"
			"                          <form action=\"/addcomment.php\" method=\"post\" name=\"UserComment\">\n"
			"                <textarea class=\"textarea\" cols=\"60\" name=\"commentText\" rows=\"7\" placeholder=\"Write a new comment\" style=\"width:786px;\"></textarea>\n"
			"                <input name=\"profileMemId\" type=\"hidden\" value=\"4449926\">\n"
			"                <input name=\"profileUsername\" type=\"hidden\" value=\"arkenthera\">\n"
			"                <div class=\"mt8\">\n"
			"                  <input class=\"inputButton btn-form-submit fs12 pt4 pb4 pl8 pr8\" name=\"commentSubmit\" type=\"submit\" value=\"Submit Comment\">\n"
			"                </div>\n"
			"              </form>\n"
			"                      </div>\n"
			"\n"
			"                                          <div class=\"comment clearfix\" id=\"comBox29814958\">\n"
			"              <a class=\"image\" href=\"http://myanimelist.net/profile/AmethystItalian\">\n"
			"                <img src=\"http://cdn.myanimelist.net/images/userimages/4312681.jpg\" width=\"48\">\n"
			"              </a>\n"
			"              <div class=\"text\">\n"
			"                <div class=\"pb8\">\n"
			"                  <a class=\"fw-b\" href=\"http://myanimelist.net/profile/AmethystItalian\">AmethystItalian</a>\n"
			"                  <span class=\"di-ib fl-r fn-grey1\">Nov 26, 2015 9:08 PM</span>\n"
			"                </div>\n"
			"                <div class=\"lh16 comment-text\" id=\"comtext29814958\">\n"
			"                  Well same thing as in it tells a love story ya :p<br />\n"
			"<br />\n"
			"Some of the later arcs are so good though! :(\n"
			"                </div>\n"
			"\n"
			"                                                                        <div class=\"postActions ar mt4\">\n"
			"\n"
			"                      \n"
			"                                            \n"
			"                                                                    <a class=\"ml8\" href=\"javascript:void(0)\" onclick=\"replyComment(29814958, 4312681)\">Reply</a>\n"
			"                      \n"
"                                                                    <a class=\"ml8\" href=\"http://myanimelist.net/comtocom.php?id1=4449926&amp;id2=4312681\">Conversation</a>\n"
"                      \n"
"                                                                    <a class=\"ml8\" href=\"javascript:void(0);\" onclick=\"deleteComment(29814958)\">Delete</a>\n"
"                      \n"
"                                                                    <a class=\"ml8\" href=\"http://myanimelist.net/modules.php?go=report&amp;type=com&amp;id=29814958\">Report</a>\n"
"                      \n"
"                    </div>\n"
"                    <div id=\"com29814958\"></div>\n"
"                  </div>\n"
"            </div>                      <div class=\"comment clearfix\" id=\"comBox29814293\">\n"
"              <a class=\"image\" href=\"http://myanimelist.net/profile/AmethystItalian\">\n"
"                <img src=\"http://cdn.myanimelist.net/images/userimages/4312681.jpg\" width=\"48\">\n"
"              </a>\n"
"              <div class=\"text\">\n"
"                <div class=\"pb8\">\n"
"                  <a class=\"fw-b\" href=\"http://myanimelist.net/profile/AmethystItalian\">AmethystItalian</a>\n"
"                  <span class=\"di-ib fl-r fn-grey1\">Nov 26, 2015 7:19 PM</span>\n"
"                </div>\n"
"                <div class=\"lh16 comment-text\" id=\"comtext29814293\">\n"
"                  Awe noticed you dropped Amagami SS :(<br />\n"
"<br />\n"
"Any specific reason why?\n"
"                </div>\n"
"\n"
"                                                                        <div class=\"postActions ar mt4\">\n"
"\n"
"                      \n"
"                                            \n"
"                                                                    <a class=\"ml8\" href=\"javascript:void(0)\" onclick=\"replyComment(29814293, 4312681)\">Reply</a>\n"
"                      \n"
"                                                                    <a class=\"ml8\" href=\"http://myanimelist.net/comtocom.php?id1=4449926&amp;id2=4312681\">Conversation</a>\n"
"                      \n"
"                                                                    <a class=\"ml8\" href=\"javascript:void(0);\" onclick=\"deleteComment(29814293)\">Delete</a>\n"
"                      \n"
"                                                                    <a class=\"ml8\" href=\"http://myanimelist.net/modules.php?go=report&amp;type=com&amp;id=29814293\">Report</a>\n"
"                      \n"
"                    </div>\n"
"                    <div id=\"com29814293\"></div>\n"
"                  </div>\n"
"            </div>          \n"
"                    <div class=\"pt16 pb8 ac\">\n"
"            <a href=\"http://myanimelist.net/comments.php?id=4449926\" class=\"btn-form-submit fs12 pt4 pb4 pl8 pr8\">All Comments</a>\n"
"          </div>\n"
"                        </div>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"                                              </div>            <!--  control container height -->\n"
"            <div style=\"clear:both;\"></div>\n"
"            <!-- end rightbody -->\n"
"          \n"
"                </div>\n"
"          <div id=\"ad-skin-bg-right\" class=\"ad-skin-side-outer ad-skin-side-bg bg-right\">\n"
"    <div id=\"ad-skin-right\" class=\"ad-skin-side right\" style=\"display: none;\">\n"
"      <div id=\"ad-skin-right-absolute-block\">\n"
"        <div id=\"ad-skin-right-fixed-block\"></div>\n"
"      </div>\n"
"    </div>\n"
"  </div></div>\n"
"    \n"
"    <footer>\n"
"  <div id=\"footer-block\">\n"
"    <div class=\"footer-link-block\">\n"
"      <p class=\"footer-link home di-ib\">\n"
"        <a href=\"http://myanimelist.net/\">Home</a>\n"
"      </p>\n"
"      <p class=\"footer-link di-ib\">\n"
"        <a href=\"http://myanimelist.net/about.php\">About</a>\n"
"        <a href=\"http://myanimelist.net/about.php?go=contact\">Support</a>\n"
"        <a href=\"http://myanimelist.net/about.php?go=advertising\">Advertising</a>\n"
"        <a href=\"http://myanimelist.net/forum/?topicid=515949\">FAQ</a>\n"
"        <a href=\"http://myanimelist.net/about/terms_of_use\">Terms</a>\n"
"        <a href=\"http://myanimelist.net/about/privacy_policy\">Privacy</a>\n"
"        <a href=\"http://myanimelist.net/about/sitemap\">Sitemap</a>\n"
"    \t</p>\n"
"  \t\t    </div>\n"
"\n"
"    <div class=\"footer-link-icon-block\">\n"
"            <div class=\"footer-social-media ac\">\n"
"        <a target=\"_blank\" class=\"icon-sns icon-fb di-ib\" href=\"https://www.facebook.com/OfficialMyAnimeList\"></a>\n"
"        <a target=\"_blank\" class=\"icon-sns icon-tw di-ib\" title=\"Follow @myanimelist on Twitter\" href=\"https://twitter.com/myanimelist\"></a>\n"
"        <a class=\"icon-sns icon-gp\" href=\"https://plus.google.com/105884801583962160252?prsrc=3\" rel=\"publisher\" target=\"_blank\" style=\"text-decoration:none;\">\n"
"          <img src=\"http://cdn.myanimelist.net/images/footer/icon-google_plus.png\" alt=\"Google+\" style=\"border:0;width:30px;height:30px;\" />\n"
"        </a>\n"
"      </div>\n"
"            <div class=\"footer-recommended ac\">\n"
"        <a target=\"_blank\" class=\"icon-recommended icon-tokyo-otaku-mode\" href=\"http://otakumode.com/fb/5aO\">Tokyo Otaku Mode</a>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div id=\"copyright\">\n"
"      MyAnimeList.net is a property of MyAnimeList, LLC. &copy;2015 All Rights Reserved.\n"
"    </div>\n"
"  </div>\n"
"</footer>\n"
"\n"
"<div id=\"evolve_footer\"></div>\n"
"\n"
"        </body>\n"
"</html>\n"
"";
#pragma endregion
		ChiStringUtil util;
		std::string test = "<div class=\"user-image mb8\"><img src=\"http://cdn.myanimelist.net/images/userimages/4449926.jpg\"></div><div class=\"user-image mb8\"><img src=\"http://cdn.myanimelist.net/images/userimages/4449926.jpg\"></div>";

		//User Image
		ChiString lookFor = "<div class=\"user-image mb8\">";
		int index = test.find(lookFor);

		if (index != -1)
		{
			ChiString img = util.ParseSubelement(output, lookFor, "</div>");
			img = util.Trim(img);
			LOGD << img;
		}


		
		RequestInterface::OnSuccess();
	}
	//----------------------------------------------------------------------------
	void MalScrapeRequest::OnError()
	{
		RequestInterface::OnError();
	}
	//----------------------------------------------------------------------------
	void MalScrapeRequest::Initialize()
	{
		m_Curl = new CurlRequest;
		m_Curl->Initialize();
		m_Curl->AddListener(this);
	}
	//----------------------------------------------------------------------------
	void MalScrapeRequest::SetUserInfo(const UserInfo& user)
	{

	}
	//----------------------------------------------------------------------------
	void MalScrapeRequest::SetOptions()
	{
		ChiString url;
		int method;
		ChiString userName;
		ChiString passWord;

		
		method = CURLOPT_HTTPGET;
		userName = Root::Get()->GetUser().GetKeyValue(kUserName);
		passWord = Root::Get()->GetUser().GetKeyValue(kPass);

		url = ("http://myanimelist.net/profile/" + userName);

		m_Curl->SetUrl(url);
		m_Curl->SetAuth(userName + ":" + passWord);
		m_Curl->SetMethod(method, "");
		m_Curl->SetWriteFunction(NULL);

		m_Curl->SetReady();
	}
	//----------------------------------------------------------------------------
	void MalScrapeRequest::Initiate()
	{

	}
	//----------------------------------------------------------------------------
}
//----------------------------------------------------------------------------